version: 1

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    
python:
  # Install our python package before building the docs
  install:
    - requirements: docs_sphinx/source/requirements_docs.txt
    - method: pip
      path: .
  system_packages: true
      
sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
